pub const FIXTURE: &[(&str, &str)] = &[
    ("BASIC", "\r,\n,\t,\u{b},\u{c},\u{7},\u{8}"),
    ("BACKSLASH", "\\"),
    ("QUOTES", "\",\\'"),
    ("SINGLE_QUOTED1", "'"),
    ("SINGLE_QUOTED2", "'"),
    ("INVALID_OCT", "\\9\\09\\"),
    ("OCT1", "\\7\\07"),
    ("OCT2", "\\53\\53"),
    ("OCT3", "\\157\\143\\164"),
    ("OCT4", "oct"),
    ("HEX", "\\x48\\x45\\x58\\x2E"),
    ("UTF16", "\\u00e4"),
    ("UTF16_PAIR", "\\uD83D\\uDE03"),
    ("UTF32_6", "\\U01F603"),
    ("UTF32_8", "\\U0001F603"),
    ("NAMED1", "\\u{Latin Capital Letter O with macron}"),
    ("NAMED2", "\\u{LATIN CAPITAL LETTER O WITH MACRON}"),
    ("NAMED3", "\\u{LATIN_CAPITAL_LETTER_O_WITH_MACRON}"),
    ("UNKNOWN", "\\/,\\z,\\ "),
    ("ESCAPED_NEWLINE", "\\\n"),
];
