pub const FIXTURE: &[(&str, &str)] = &[
    ("EMPTY", ""),
    ("FOO", "foo"),
    ("VAR1S", "foo"),
    ("VAR1E", "was unset or empty"),
    ("VAR1U", "was unset or empty"),
    ("VAR2", "foo"),
    ("VAR3S", "foo"),
    ("VAR3E", ""),
    ("VAR3U", "was unset"),
    ("VAR4S", "was not empty"),
    ("VAR4E", ""),
    ("VAR4U", ""),
    ("VAR5S", "was set"),
    ("VAR5E", "was set"),
    ("VAR5U", ""),
    ("VAR6", "double quoted"),
    ("VAR7", "single quoted"),
    ("VAR8", "\\n"),
];
