pub const FIXTURE: &[(&str, &str)] = &[
    ("EMPTY", ""),
    ("FOO", "foo"),
    ("VAR1S", "foo"),
    ("VAR1E", ""),
    ("VAR1U", "was unset or empty"),
    ("VAR2", "${UNSET:-${UNSET:-${UNSET:-${UNSET:-${UNSET:-${UNSET:-$FOO}}}}}}"),
    ("VAR3S", ""),
    ("VAR3E", ""),
    ("VAR3U", ""),
    ("VAR4S", "${FOO:+was not empty}"),
    ("VAR4E", "${EMPTY:+was not empty}"),
    ("VAR4U", "${UNSET:+was not empty}"),
    ("VAR5S", ""),
    ("VAR5E", ""),
    ("VAR5U", ""),
    ("VAR6", "\"double quoted\""),
    ("VAR7", "'single quoted'"),
    ("VAR8", "\\n"),
];
